CREATE OR REPLACE TRIGGER VerificaEtaProprietario
BEFORE INSERT ON Proprietario
FOR EACH ROW
DECLARE
    DN DATE;
    MINORENNE EXCEPTION;
    MAGGIORENNE EXCEPTION;
BEGIN
    SELECT DataNascitaPersona 
    INTO DN
    FROM PERSONA 
    WHERE CFPersona = :new.CFPersona;

    IF (SYSDATE - DN) / 365.25 < 18
        THEN
        RAISE MINORENNE;
    END IF;

EXCEPTION 
WHEN MINORENNE THEN
RAISE_APPLICATION_ERROR(-20000,'Proprietario minorenne');

END VerificaEtaProprietario;
