CREATE OR REPLACE PROCEDURE eliminaCorsoInattivo (NomePal in  varchar) IS
CFISTR varchar(16);

BEGIN

 for r in(
SELECT NOMECORSO
FROM CORSO
WHERE NOMECORSO NOT IN (SELECT DISTINCT NOMECORSO
FROM PRENOTAZIONE 
WHERE NOMEPALESTRA = NomePal AND DATAPRENOTAZIONE >= ADD_MONTHS(SYSDATE,-12)) AND NOMEPALESTRA = NomePal
 )
 
LOOP


SELECT ISTRUTTORE.CFPersona
INTO CFISTR
FROM Istruttore INNER JOIN CONTRATTO ON ISTRUTTORE.CFPERSONA = CONTRATTO.CFPERSONA
WHERE SPECIALIZZAZIONEISTRUTTORE = r.NOMECORSO AND CONTRATTO.NOMEPALESTRA = NOMEPAL AND CONTRATTO.DATASCADENZACONTRATTO > SYSDATE;


DELETE FROM CONDUCE WHERE CFPERSONA = CFISTR;
DELETE FROM PRENOTAZIONE WHERE NOMECORSO = r.NOMECORSO AND NOMEPALESTRA = NomePal;
DELETE FROM CORSO WHERE NOMECORSO = r.NOMECORSO AND NOMEPALESTRA = NomePal;

UPDATE CONTRATTO
SET DATASCADENZACONTRATTO = SYSDATE
WHERE CFPERSONA = CFISTR AND DATASCADENZACONTRATTO > SYSDATE;

EXCEPTION
      WHEN NO_DATA_FOUND THEN
      DBMS_OUTPUT.PUT_LINE('La palestra non ha corsi inattivi.');
END LOOP;


 END;